version: "3.7"

services:
  events-server:
    image: events-server-image
    volumes:
      - .:/events-server:cached
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=12345678

  db:
    restart: always
    container_name: db
    image: postgres:10-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_DBPASSWORD}"
    ports:
      - 5436:5432
